backend:
  image:
    repository: ghcr.io/tues-2026-pbl-11-klas/365-days-of-art-backend
    tag: c2d88ede70dc01b527bb15745da6baf355c1e694

frontend:
  image:
    repository: ghcr.io/tues-2026-pbl-11-klas/365-days-of-art-frontend
    tag: c2d88ede70dc01b527bb15745da6baf355c1e694
