backend:
  image:
    repository: ghcr.io/tues-2026-pbl-11-klas/365-days-of-art-backend
    tag: dcb097b41fbb95cb9eb1f16bd24b21f4ce5f786d

frontend:
  image:
    repository: ghcr.io/tues-2026-pbl-11-klas/365-days-of-art-frontend
    tag: dcb097b41fbb95cb9eb1f16bd24b21f4ce5f786d
